# Generated by Django 5.2.6 on 2025-09-17 20:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sporty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exercise_type', models.CharField(choices=[('pushup', 'Push-up'), ('squat', 'Squat'), ('plank', 'Plank'), ('jumping_jacks', 'Jumping Jacks'), ('burpees', 'Burpees'), ('lunges', 'Lunges'), ('mountain_climbers', 'Mountain Climbers'), ('high_knees', 'High Knees'), ('sit_ups', 'Sit-ups'), ('pull_ups', 'Pull-ups')], max_length=50)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='exercise_videos/')),
                ('video_url', models.URLField(blank=True, max_length=500, null=True)),
                ('repetitions_count', models.IntegerField(default=0)),
                ('form_score', models.FloatField(default=0.0, help_text='Score from 0-10 for exercise form')),
                ('duration', models.FloatField(default=0.0, help_text='Duration in seconds')),
                ('calories_burned', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_analyzed', models.BooleanField(default=False)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_uploads', to='sporty.athleteprofile')),
            ],
            options={
                'db_table': 'exercise_uploads',
                'ordering': ['-created_at'],
            },
        ),
    ]
